# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: GenerateDeps

on:
  workflow_dispatch:
  schedule:
   - cron: '0 7 * * 1'

jobs:
  "Generate-Deps":
    runs-on: "ubuntu-latest"
    steps:
      - id: step-0
        name: check-out
        uses: actions/checkout@v3
        with:
          ref: main
      - id: step-1
        name: setup-java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - id: step-2
        name: create-branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        with:
          branch: generate-deps
        env:
          GITHUB_TOKEN: {{ secrets.GITHUB_TOKEN }}
      - id: step-3
        name: gradle generate deps
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test --tests BundledDependenciesTest.generateDeps
        env:
          GENERATE_DEPS: true
      - id: step-4
        name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: noreply@github.com
          message: Refresh versions.properties
          new_branch: dependency-update
          push: --force --set-upstream origin dependency-update
      - id: step-5
        name: Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: dependency-update
          destination_branch: main
          pr_title: Upgrade gradle dependencies
          pr_body: 'refreshDeps has found those library updates!'
          pr_draft: true
          github_token: {{ secrets.GITHUB_TOKEN }}
